### ISSUE TITLE
计划呢？

### ISSUE THREAD

**Issue by zyh226** [tshwangq/awesome-smoking#1]
计划呢？

**Comment by tshwangq** [comment]
考虑到戒烟的难度，我先记录抽烟习惯。
记录在smoking.org 里面的，　要抽烟就先记录一笔todo

后续在延长抽烟时间

**Comment by tshwangq** [comment]
事实证明，只有在吸烟者的时候需要计划．
非吸烟者就是非吸烟者了．　保持这个身份就是所有的计划
